### ISSUE TITLE
Smart Gateway doesn't connect to secured ElasticSearch service

### ISSUE THREAD

**Issue by leifmadsen** [redhat-service-assurance/smart-gateway#32]
When connecting the Smart Gateway to an ECL deployed ElasticSearch, the ElasticSearch service (connection) is setup for a secured connection. However, I don't believe the Smart Gateway is currently designed to connect to a secure endpoint.

> **Sidenote** we're not calling out a specific version/branch of ElasticSearch either, so we should also resolve that --> https://github.com/olivere/elastic#elastic-50
> 
> See https://github.com/redhat-service-assurance/smart-gateway/blob/master/internal/pkg/saelastic/client.go#L8
> 
> Just need to validate that we align our call out with the version of ElasticSearch we plan to implement, which is looking like ElasticSearch v5 (the library seems to assume v6 I believe).

The connection to ElasticSearch is done in the client setup here: https://github.com/redhat-service-assurance/smart-gateway/blob/master/internal/pkg/saelastic/client.go#L57

I have not investigated exactly how this should be resolved, but here are links that are related to the problem that others have also requested:

* https://github.com/olivere/elastic/issues/636
* https://github.com/olivere/elastic/issues/738
* https://github.com/olivere/elastic/wiki

Our current custom resource manifest for connecting to ElasticSearch from the Smart Gateway (via Operator) looks like this:

```
apiVersion: smartgateway.infra.watch/v1alpha1
kind: SmartGateway
metadata:
  name: events
spec:
  size: 1
  amqp_url: qdr-white.sa-telemetry.svc.cluster.local:5672/collectd/telemetry
  elastic_url: https://elasticsearch.sa-telemetry.svc:9200
  debug: "false"
  service_type: "events"
  container_image_path: 172.30.1.1:5000/sa-telemetry/smart-gateway
# vim: set tabstop=2 shiftwidth=2 expandtab smartindent:
```
Our custom resource manifest for the elasticsearch-operator looks like the following:

```
---
apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
spec:
  managementState: "Managed"
  nodeSpec:
    image: quay.io/openshift/origin-logging-elasticsearch5:latest
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
  nodes:
  - nodeCount: 2
    roles:
    - client
    - data
    - master
    storage: {}
  redundancyPolicy: SingleRedundancy
```
